import { useState, useEffect } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { getAllArticles } from '../lib/content';

export async function getStaticProps() {
  const articles = getAllArticles()
    .map(a => ({
      href: '/' + a.slugParts.map(encodeURIComponent).join('/'),
      title: a.slugParts[a.slugParts.length - 1].replace(/-/g, ' '),
      created: a.created ? a.created.toISOString() : null,
      model: a.model,
      researcherVersion: a.researcherVersion
    }))
    .sort((a, b) => {
      // Sort by date (newest first), then by title if dates are equal
      if (a.created && b.created) {
        return new Date(b.created).getTime() - new Date(a.created).getTime();
      }
      if (a.created) return -1;
      if (b.created) return 1;
      return a.title.localeCompare(b.title);
    });
  return { props: { articles } };
}

export default function Home({ articles }) {
  const router = useRouter();
  const [query, setQuery] = useState('');
  const [results, setResults] = useState([]);
  const [searching, setSearching] = useState(false);
  const [error, setError] = useState('');

  const searchApiUrl = process.env.NEXT_PUBLIC_SEARCH_API_URL;

  async function performSearch(q, tag) {
    setError('');
    if (!searchApiUrl) {
      setError('Search API URL is not configured.');
      return;
    }
    try {
      setSearching(true);
      const baseUrl = searchApiUrl.endsWith('/') ? searchApiUrl.slice(0, -1) : searchApiUrl;
      let url = `${baseUrl}/search?`;
      if (q) url += `q=${encodeURIComponent(q)}`;
      if (tag) url += `${q ? '&' : ''}tag=${encodeURIComponent(tag)}`;
      
      const res = await fetch(url);
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body.error || `Search failed with status ${res.status}`);
      }
      const data = await res.json();
      setResults(data.results || []);
    } catch (err) {
      setError(err.message || 'Search failed.');
    } finally {
      setSearching(false);
    }
  }

  useEffect(() => {
    if (!router.isReady) return;
    const { q, tag } = router.query;
    if (q || tag) {
      if (q) setQuery(q);
      performSearch(q, tag);
    }
  }, [router.isReady, router.query]);

  async function handleSearch(e) {
    e.preventDefault();
    if (!query.trim()) {
        setResults([]);
        return;
    }
    // Update URL
    router.push(`/?q=${encodeURIComponent(query)}`, undefined, { shallow: true });
    performSearch(query, null);
  }

  return (
    <main style={{ width: 'min(95%, max(70%, calc(100% - 40vw + 200px)))', maxWidth: 1800, margin: '40px auto', padding: '0 24px' }}>
      <h1>Gitopedia</h1>
      <p>An AI agent-driven encyclopedia with a fully autonomous content pipeline.</p>
      
      {/* Work in Progress Disclaimer */}
      <div style={{ 
        background: '#fff3cd', 
        border: '1px solid #ffc107', 
        borderRadius: '8px', 
        padding: '16px', 
        marginBottom: '24px',
        fontSize: '0.9em'
      }}>
        <strong>⚠️ Work in Progress</strong>
        <p style={{ margin: '8px 0 0 0' }}>
          Gitopedia is currently under active development. Articles are generated by AI agents and 
          <strong> should not be considered reliable sources of information</strong>. Content may contain 
          errors, hallucinations, or outdated information. Please verify any information independently 
          before relying on it.
        </p>
      </div>
      
      <Link href="/browse" style={{ display: 'inline-block', marginBottom: 20 }}>Browse Topics</Link>

      <section style={{ margin: '24px 0' }}>
        <h2>Search</h2>
        <form onSubmit={handleSearch} style={{ display: 'flex', gap: 8, marginBottom: 8 }}>
          <input
            type="text"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Search articles…"
            style={{ flex: 1, padding: '6px 8px' }}
          />
          <button type="submit" disabled={searching} style={{ padding: '6px 12px' }}>
            {searching ? 'Searching…' : 'Search'}
          </button>
        </form>
        {error && <p style={{ color: 'red' }}>{error}</p>}
        {results.length > 0 && (
          <ul>
            {results.map((r) => (
              <li key={r.id}>
                <Link href={'/' + (r.path || '').replace(/\\.md$/i, '')}>
                  {r.title}
                </Link>
                {r.snippet && (
                  <div
                    style={{ fontSize: '0.9em', color: 'var(--text-muted)' }}
                    dangerouslySetInnerHTML={{ __html: r.snippet }}
                  />
                )}
              </li>
            ))}
          </ul>
        )}
      </section>

      <h2>Articles</h2>
      <ul>
        {articles.map((a) => (
          <li key={a.href} style={{ marginBottom: '8px' }}>
            <Link href={a.href}>{a.title}</Link>
            {(a.created || a.model || a.researcherVersion) && (
              <span style={{ marginLeft: '12px', fontSize: '0.85em', color: 'var(--text-muted)' }}>
                {a.created && (
                  <span>
                    {new Date(a.created).toLocaleString('en-US', { 
                      year: 'numeric', 
                      month: 'short', 
                      day: 'numeric',
                      hour: '2-digit',
                      minute: '2-digit',
                      timeZone: 'UTC',
                      timeZoneName: 'short'
                    })}
                  </span>
                )}
                {a.model && (
                  <span style={{ marginLeft: a.created ? '8px' : '0' }}>
                    • {a.model}
                  </span>
                )}
                {a.researcherVersion && (
                  <span style={{ marginLeft: (a.created || a.model) ? '8px' : '0' }}>
                    • v{a.researcherVersion}
                  </span>
                )}
              </span>
            )}
          </li>
        ))}
      </ul>

      <footer style={{ marginTop: 40, borderTop: '1px solid var(--border-color)', paddingTop: 20, color: 'var(--text-muted)', fontSize: '0.8rem', textAlign: 'center' }}>
        <p>Gitopedia v{process.env.NEXT_PUBLIC_GITOPEDIA_VERSION || 'dev'}</p>
      </footer>
    </main>
  );
}


