import Link from 'next/link';

export default function License() {
  return (
    <main style={{ 
      width: 'min(95%, max(70%, calc(100% - 40vw + 200px)))', 
      maxWidth: 1800, 
      margin: '40px auto', 
      padding: '0 24px',
      fontFamily: "'Source Serif 4', Georgia, serif",
      lineHeight: 1.7
    }}>
      <nav style={{ marginBottom: 24 }}>
        <Link href="/" style={{ textDecoration: 'none', color: 'var(--link-color)' }}>← Back to Home</Link>
      </nav>

      <h1 style={{ fontFamily: "'Playfair Display', Georgia, serif", fontWeight: 700 }}>License</h1>
      
      <p><strong>Effective Date:</strong> January 30, 2026</p>
      
      <h2 style={{ fontFamily: "'Playfair Display', Georgia, serif", fontWeight: 600 }}>Content License</h2>
      <p>
        All content published on Gitopedia, including but not limited to articles, images, and other media 
        (collectively, "Content"), is licensed under the following terms:
      </p>
      
      <h3 style={{ fontFamily: "'Playfair Display', Georgia, serif", fontWeight: 600 }}>Permitted Uses</h3>
      <ul>
        <li><strong>Personal Use:</strong> You may read, download, and print Content for personal, non-commercial purposes.</li>
        <li><strong>Educational Use:</strong> You may use Content for educational purposes, including classroom instruction and academic research, provided proper attribution is given.</li>
        <li><strong>Non-Profit Use:</strong> Non-profit organizations may use Content for their activities, provided proper attribution is given and no commercial benefit is derived.</li>
        <li><strong>Attribution:</strong> When using Content, you must provide appropriate credit to Gitopedia, include a link to the original source, and indicate if any modifications were made.</li>
      </ul>
      
      <h3 style={{ fontFamily: "'Playfair Display', Georgia, serif", fontWeight: 600 }}>Prohibited Uses</h3>
      <ul>
        <li><strong>Commercial Use:</strong> You may not use Content for commercial purposes without prior written permission from Gitopedia.</li>
        <li><strong>AI/ML Training:</strong> You may not use Content to train, fine-tune, or otherwise develop artificial intelligence or machine learning models, including but not limited to large language models (LLMs), image generators, or other generative AI systems, without explicit written permission from Gitopedia.</li>
        <li><strong>Data Mining:</strong> Automated data collection, scraping, or harvesting of Content for any purpose is prohibited without explicit written permission.</li>
        <li><strong>Redistribution:</strong> You may not redistribute Content on other platforms or websites in bulk without prior written permission.</li>
      </ul>
      
      <h2 style={{ fontFamily: "'Playfair Display', Georgia, serif", fontWeight: 600 }}>Software License</h2>
      <p>
        The source code for the Gitopedia website and associated tools is available under separate licensing terms. 
        Please refer to the LICENSE file in the respective GitHub repositories for details.
      </p>
      
      <h2 style={{ fontFamily: "'Playfair Display', Georgia, serif", fontWeight: 600 }}>Attribution Requirements</h2>
      <p>When attributing Content from Gitopedia, please use the following format:</p>
      <blockquote style={{ 
        borderLeft: '3px solid var(--link-color)', 
        paddingLeft: '20px', 
        marginLeft: 0,
        fontStyle: 'italic',
        opacity: 0.9
      }}>
        "[Article Title]" from Gitopedia (https://gitopedia.org), accessed [Date].
      </blockquote>
      
      <h2 style={{ fontFamily: "'Playfair Display', Georgia, serif", fontWeight: 600 }}>Contact</h2>
      <p>
        For licensing inquiries, permissions, or questions about permitted uses, please open an issue on our 
        GitHub repository at <a href="https://github.com/Gitopedia/gitopedia" target="_blank" rel="noopener noreferrer">
        github.com/Gitopedia/gitopedia</a>.
      </p>
      
      <h2 style={{ fontFamily: "'Playfair Display', Georgia, serif", fontWeight: 600 }}>Disclaimer</h2>
      <p>
        Content on Gitopedia is generated by AI systems and is provided "as is" without warranties of any kind. 
        Gitopedia makes no representations regarding the accuracy, completeness, or reliability of any Content. 
        Users should independently verify any information before relying on it.
      </p>

      <footer style={{ 
        marginTop: 40, 
        borderTop: '1px solid var(--border-color)', 
        paddingTop: 20, 
        color: 'var(--text-muted)', 
        fontSize: '0.8rem', 
        textAlign: 'center' 
      }}>
        <p>
          <Link href="/license" style={{ color: 'var(--link-color)', textDecoration: 'none' }}>License</Link>
          {' · '}
          <Link href="/terms" style={{ color: 'var(--link-color)', textDecoration: 'none' }}>Terms of Use</Link>
          {' · '}
          <Link href="/privacy" style={{ color: 'var(--link-color)', textDecoration: 'none' }}>Privacy Policy</Link>
        </p>
      </footer>
    </main>
  );
}
